### ISSUE TITLE
Search & replace ?

### ISSUE THREAD

**Issue by Thorium** [ChrSteinert/ArrayPrinter#4]
I remember when I was kid, when playing a computer game, when I notice I have game money for example $1,715,320 then I saved the game, and opened hex editor. (I think it was PC-Tools, but it might have been some other too.) That sum for hex is 1A 2C 78. So I did search the saved file for that and if found, I tried to replace the bytes with some other, let's say FF FF FF, which is $16,777,215. And then I opened the game and loaded my save, seeing if my money had changed. Did work sometimes, but sometimes not.

As for nostalgic trip, what is the way for doing "search" and "search & replace" with ArrayPrinter ?
Would you think it would be nice feature to add those functions, or is it totally out of scope of this project?

**Comment by Thorium** [comment]
The fastest way to search and replace these are probably ReadOnlySpan<byte>, so it can be done like this:

```fsharp
open System
open System.Linq

// Some data
let mybytes = "I have money ,x and that's a lot"B

// Something to search
let hexValue = String.Format("{0:X}", 1_715_320)  // "1A2C78"

let searchTarget = hexValue |> Convert.FromHexString // [|26uy; 44uy; 120uy|]

let position = (ReadOnlySpan<byte> mybytes).IndexOf(ReadOnlySpan<byte> searchTarget) // found, pos: 13

let replaceValue = "FFFFFF" |> Convert.FromHexString // [|255uy; 255uy; 255uy|]

let newBytes =
    (ReadOnlySpan<byte> mybytes).Slice(0, position).ToArray().Concat(
        (ReadOnlySpan<byte> replaceValue).ToArray()).Concat(
        (ReadOnlySpan<byte> mybytes).Slice(
            position + searchTarget.Length,
            mybytes.Length - position - searchTarget.Length).ToArray()
        ).ToArray()


// newBytes |> System.Text.Encoding.ASCII.GetString
// "I have money ??? and that's a lot"
```

Maybe better to keep this as separate code, and focus ArrayPrinter to be minimalistic print-only.

**Comment by ChrSteinert** [comment]
I’d also rather keep it a formatted/console printer. 

But thanks for the story! :)
